=== williamlwclwc/Stendhal_S1Team09/data/conf/actions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/actions" elementFormDefault="qualified"
	xmlns:Q1="stendhal">
	
	<!-- Root element (a group of actions) -->
	<element name="actions" type="Q1:actionGroup" />
	
	<!-- Element type to represent a group of actions -->
	<complexType name="actionGroup">
		<sequence>
			<element name="action" type="Q1:actionType" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<!-- Element type to represent an action -->
	<complexType name="actionType">
		<sequence>
			<element name="implementation" type="Q1:implementation" />
			<element name="parameters" type="Q1:parameters" minOccurs="0" maxOccurs="1" />
			<element name="remainder" type="Q1:remainder" minOccurs="0" maxOccurs="1" />
		</sequence>
		<attribute name="name" type="string" use="required" />
		<attribute name="minimumParameters" type="nonNegativeInteger" default="0" />
		<attribute name="maximumParameters" type="nonNegativeInteger" default="0" />
	</complexType>

	<!-- Element type for specifying the class which implements the action -->
	<complexType name="implementation">
		<attribute name="class-name" type="string" />
	</complexType>
	
	<!-- Element type to represent a list of command parameters -->
	<complexType name="parameters">
		<sequence>
			<element name="parameter" type="Q1:parameter" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<!-- Element type to represent a command parameter -->
	<complexType name="parameter">
		<attribute name="name" type="string" />
		<attribute name="index" type="nonNegativeInteger" />
	</complexType>
	
	<!-- Element type to represent the 'remainder' (the text after the parameters) -->
	<complexType name="remainder">
		<attribute name="name" type="string" />
	</complexType>
	
</schema>

=== williamlwclwc/Stendhal_S1Team09/data/conf/actions.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal actions.xsd ">
	
	<action name="who">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
	</action>

	<action name="where">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
	  <remainder name="target" />
	</action>

	<action name="teleport" minimumParameters="4" maximumParameters="4">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
	  <parameters>
		<parameter name="target" index="0" />
		<parameter name="zone" index="1" />
		<parameter name="x" index="2" />
		<parameter name="y" index="3" />
	  </parameters>
	</action>


    <!-- AcceptChallenge.java -->
    <action name="acceptChallenge" minimumParameters="1" maximumParameters="1">
      <implementation class-name="games.stendhal.client.actions.SlashAction" />
      <parameters>
        <parameter name="target" index="0" />
      </parameters>
      <!-- Not sure about this but I think this has not yet been implemented -->
      <!-- <remainder name="action" index="challenge"/>  -->
    </action>
    
    
    <!-- AddBuddyAction -->
    <!-- Contain condition, function not implemented yet -->
    <!--     <action name="addBuddy" minimumParameters="1" maximumParameters="1">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
      <parameters>
        <parameter name="target" index="0" />
      </parameters>
    </action> -->

    <!-- AdminLevelAction -->
    <action name="adminLevel" minimumParameters="1" maximumParameters="2">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
      <parameters>
        <parameter name="target" index="0" />
        <!-- Not sure about this -->
        <parameter name="newlevel" index="1" />
      </parameters>
    </action>

    <!-- AdminNoteAction -->
    <action name="adminNote" minimumParameters="1" maximumParameters="1">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
      <parameters>
        <parameter name="target" index="0" />
      </parameters>
      <!-- Not sure about this -->
      <remainder name="note" />
    </action>   

    <!-- AlterAction -->
    <action name="alter" minimumParameters="3" maximumParameters="3">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
      <parameters>
        <parameter name="target" index="0" />
        <parameter name="stat" index="1" />
        <parameter name="mode" index="2" />
      </parameters>
      <!-- Not sure about this -->
      <remainder name="value" />
    </action>
	
	<!-- AlterCreatureAction -->
    <action name="alterCreature" minimumParameters="2" maximumParameters="2">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
      <parameters>
        <parameter name="target" index="0" />
        <parameter name="stat" index="1" />
      </parameters>
    </action>

    <!-- AlterQuestAction -->
    <!-- Contain condition, function not implemented yet -->
    <!--     <action name="alterQuest" minimumParameters="3" maximumParameters="2">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
      <parameters>
        <parameter name="target" index="0" />
        <parameter name="name" index="1" />
        <parameter name="state" index="2" />
      </parameters>
    </action> -->

    <!-- AnswerAction -->
    <action name="answer" minimumParameters="1" maximumParameters="0">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
      <!-- Not sure about this -->
      <remainder name="text" />
    </action>

    <!-- AtlasBrowserLaunchCommand -->
    <!-- Not a basic simple class, will be implemented later -->
    <!--     <action name="alter">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
    </action> -->

    <!-- AutoWalkAction -->
    <!-- Not a basic key/pair class -->
    <!--<action name="autoWalk">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
    </action>  -->

    <!-- AutoWalkStopAction -->
    <!-- Not a basic key/pair class -->
    <!--<action name="autoWalkStop">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
      <remainder name="stop" />
    </action>  -->
    
    <!-- AwayAction -->
    <!-- Contain condition, function not implemented yet -->
    <!--     <action name="away">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
      <remainder name="message" />
    </action> -->
    
    <!-- BanAction -->
    <action name="ban" minimumParameters="2" maximumParameters="2">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
      <parameters>
        <parameter name="target" index="0" />
        <parameter name="hours" index="1" />
      </parameters>
      <!-- Not sure about this -->
      <remainder name="reason" />
    </action>   
    
    <!-- BareBonesBrowserLaunchCommand -->
    <!-- Not a simple key/pair class -->
    <!-- <action name="bareBoneBrowserCommand">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
    </action>    -->
    
    <!-- CastSpellAction -->
    <!-- Contain condition which has not been implemented yet -->
    <!-- <action name="castSpell" minimumParameters="2" maximumParameters="2">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
      <parameters>
        <parameter name="baseitem" index="0" />
      </parameters>
      <remainder name="baseslot" index="spells"/>
    </action>    -->
    
    <!-- ClearChatLogAction -->
    <action name="clearChatLog">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
    </action>   
    
    <!-- ClickModeAction -->
    <!-- Not a basic class, contains condition -->
    <!-- <action name="clickMode">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
    </action>   --> 
    
    <!-- ClientInfoAction -->
    <!-- Not a basic class, contains condition -->
    <!-- <action name="clientInfo">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
    </action>    -->
    
    <!-- ConfigAction -->
    <!-- Contain condition, not a basic class -->
    <!-- <action name="config" minimumParameters="1" maximumParameters="1">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
    </action>    -->
	
	<!-- CreateChallengeAction -->
    <action name="createChallenge" minimumParameters="1" maximumParameters="1">
	  <implementation class-name="games.stendhal.client.actions.SlashAction" />
      <parameters>
        <parameter name="target" index="0" />
      </parameters>
      <!-- Not sure about this but I think this has not yet been implemented -->
      <!-- <remainder name="action" index="open"/>  -->
    </action>   
</actions>

=== williamlwclwc/Stendhal_S1Team09/tests/games/stendhal/client/core/config/testaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal actions.xsd ">
	
	<action name="whoTest">
	  <implementation class-name="games.stendhal.client.actions.SimpleAction" />
	</action>

	<action name="whereTest">
	  <implementation class-name="games.stendhal.client.actions.SimpleAction" />
	  <remainder name="target" />
	</action>

	<action name="teleportTest" minimumParameters="4" maximumParameters="4">
	  <implementation class-name="games.stendhal.client.actions.SimpleAction" />
	  <parameters>
		<parameter name="target" index="0" />
		<parameter name="zone" index="1" />
		<parameter name="x" index="2" />
		<parameter name="y" index="3" />
	  </parameters>
	</action>
</actions>
